export enum ShoppingCartActionType {
  GET_SUMMARY = 'GET_SUMMARY',
  GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS',
  GET_SUMMARY_ERROR = 'GET_SUMMARY_ERROR',
  /*    ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART',
    REMOVE_FROM_SHOPPING_CART = 'REMOVE_FROM_SHOPPING_CART',*/
}
