export enum SecurityComponents {
  GeneralConfiguration = 'GeneralConfiguration',
  SideBarMenuItems = 'SideBarMenuItemsConfiguration',
  SubMenuItemsConfiguration = 'SubMenuItemsConfiguration',
  AppRoutes = 'AppRoutes',
  OffererSolicitationNavHeader = 'OffererSolicitationNavHeader',
  OffererSolicitationRequestedFiles = 'OffererSolicitationRequestedFiles',
  OffererRolesList = 'OffererRolesList',
  OffererSolicitationActivity = 'OffererSolicitationActivity',
  CompanyHeader = 'CompanyHeader',
  CompanySolicitationPage = 'CompanySolicitationPage',
  CompanySolicitationActivity = 'CompanySolicitationActivity',
  CompanySolicitationRequestedFiles = 'CompanySolicitationRequestedFiles',
  OffererSolicitationDataAnalysisDetail = 'OffererSolicitationDataAnalysisDetail',
  OffererSolicitationApproval = 'OffererSolicitationApproval',
  OffererSolicitationDocumentationAnalysis = 'OffererSolicitationDocumentationAnalysis',
  OffererSolicitationDocumentationValidation = 'OffererSolicitationDocumentationValidation',
  OffererLineHome = 'HomeOffererLine',
  OffererProductLineDetailPage = 'ProductLineDetailPage',
  FilingsPage = 'Filings',
  OffererSolicitationBureau = 'OffererSolicitationBureau',
  OffererSolicitationExternal = 'OffererSolicitationExternal',
  HomeCompanyPage = 'HomeCompanyPage',
  OffererIntegration = 'OffererIntegration',
  HomeOffererClientPortfolio = 'HomeOffererClientPortfolio',
  HomeOffererTemplates = 'HomeOffererTemplates',
  OffererDocumentation = 'OffererDocumentation'
}
