name: "🚀 Deploy Stage TEST"

run-name: Deploy Stage ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version (vX.X.X)'
        required: true

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    # Vinculamos con el entorno de GitHub para usar las secrets correspondientes
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Front release asset
        run: |
          gh release download ${{ inputs.version }} \
            --pattern "front-${{ inputs.version }}.zip" \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip Front artifact
        run: unzip front-${{ inputs.version }}.zip
        
      - name: Inyectar Scripts con Perl
        env:
          SCRIPTS_CONTENT: ${{ secrets.INDEX_POST_BUILD_SCRIPTS }}
          SEARCH: "<!--INDEX_POST_BUILD_SCRIPTS-->"
        run: |
          perl -i -0777 -pe 's/$ENV{SEARCH}/$ENV{SCRIPTS_CONTENT}/g' build/index.html
    
      - name: Deploy Test File to Stage
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: /tests-build/
