name: "🚀 Deploy Production"

run-name: Deploy Production ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version (vX.X.X)'
        required: true
        
jobs:
  enable-maintenance:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4
      
      - name: 📝 Prepare Maintenance Page
        run: |
          mkdir ./maintenance_only
          cp ./design/sites/app_offline.htm ./maintenance_only/
          
      - name: 🚧 Upload Maintenance Page
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './maintenance_only'
          target-path: ''
          # NO BORRAR: Mucho muy importante (sin esta linea de abajo te borra todo el contenido del server)
          clean: false
          
  deploy-production:
    needs: enable-maintenance
    runs-on: ubuntu-latest
    # Vinculamos con el entorno de GitHub para usar las secrets correspondientes
    environment: production
    
    steps:            
      - name: 📂 Checkout code
        uses: actions/checkout@v4
        
      - name: ☁️ Download Front release asset
        run: |
          gh release download ${{ inputs.version }} \
            --pattern "front-${{ inputs.version }}.zip" \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: 🔓 Unzip Front artifact
        run: unzip front-${{ inputs.version }}.zip

      # Se exluyen archivos que no se deben pisar
      - name: 🧹 Clean and Filter Package
        run: |
          rm -f ./build/configuration.js
          rm -f ./build/manifest.json
          rm -f ./build/web.config

      - name: 🔍 Inject Google Site Verification
        env:
          SCRIPTS_CONTENT: ${{ secrets.INDEX_GOOGLE_SITE_VERIFICATION }}
          SEARCH: 'google-site-verification-post-build'
        run: |
          perl -i -0777 -pe 's/$ENV{SEARCH}/$ENV{SCRIPTS_CONTENT}/g' build/index.html
        
      - name: 📊 Inject Analytics Scripts with Perl
        env:
          SCRIPTS_CONTENT: ${{ secrets.INDEX_POST_BUILD_SCRIPTS }}
          SEARCH: '<script id="index-post-build-scripts"></script>'
        run: |
          perl -i -0777 -pe 's/$ENV{SEARCH}/$ENV{SCRIPTS_CONTENT}/g' build/index.html
          
      - name: 🚀 Deploy Front to Production
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./build
          target-path: ''
          # NO BORRAR: Mucho muy importante (sin esta linea de abajo te borra todo el contenido del server)
          clean: false
